version: '3'
services:
  wiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./LocalSettings.php:/home/sysadmin/LocalSettings.php
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: DEP@ssw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume: